#!/bin/sh -e
#
# variscite bluetooth 
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# This script activate the Bluetooth for Variscite SOM MX6
# I/O

#Check if device exist
(dmesg | grep -q "tuple 0x91") # Check if BT/WIFI is up
if [ $? -eq 0 ]
then
	echo "BT found"
else
	echo "No BT found"
	exit 0
fi

echo 178 >/sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio178/direction
echo 0 > /sys/class/gpio/gpio178/value
sleep 0.1
echo 1 > /sys/class/gpio/gpio178/value

hciattach -t 10 -s 115200 /dev/ttymxc1 texas 3000000

/usr/libexec/bluetooth/bluetoothd &

hciconfig hci0 up

exit 0
