#! /bin/sh
#
#
# Filename: alsa-state-init
# save alsa state for first time


asound_store(){
	echo "ALSA: Storing mixer settings..."
	if test -x /usr/sbin/alsactl
	then
		/usr/sbin/alsactl -f /var/lib/alsa/asound.state store
		rm -f /etc/rcS.d/S02variscite-alsa-init
	fi
}

case "$1" in
start)		asound_store ;;
stop)		asound_store ;;
esac
