#!/bin/sh -e
#
# variscite touch 
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# This script disable the build in spi ADS7846 Touchscreen in case ctw6120-tsc
# I/O

#Check if device exist
(dmesg | grep -q " CTW6120: revid 0 touchscreen")  # Check ifctw6120-tsc
if [ $? -eq 0 ]
then
	echo "CTW6120 found disabling ADS784"
	export DISPLAY=:0.0
	xinput disable "ADS7846 Touchscreen"
fi

exit 0
