#!/bin/sh -e
#
# variscite touch 
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# This script disable the build in spi ADS7846 Touchscreen in case ctw6120-tsc
# I/O
#
#Check if device exist
#
#Work around
cp /etc/pointercal.xinput.new /etc/pointercal.xinput
touch /etc/pointercal.xinput
chmod 444 /etc/pointercal.xinput

(dmesg | grep " CTW6120: revid 0 touchscreen")  # Check ifctw6120-tsc
if [ $? -eq 0 ]      # check exit code; if 0 No BT else BT
then
echo "CTW6120 found disabling ADS784"
export DISPLAY=:0.0
xinput disable "ADS7846 Touchscreen"
fi
#
#
exit 0
