#!/bin/bash

. /etc/wifi/variscite-wifi.conf
. /etc/wifi/variscite-wifi-common.sh

#################################################
#              Execution starts here            #
#################################################

# Exit if booting from SD on DART-IMX8M
if grep -q MX8M /sys/devices/soc0/soc_id && \
   grep -q mmcblk1 /proc/cmdline; then
	exit 0
fi

# Enable ethernet and exit if booting from eMMC without WIFI
if grep -q MX8M /sys/devices/soc0/soc_id && \
   ! grep -q WIFI /sys/devices/soc0/machine ; then
	modprobe fec
	exit 0
fi

# Exit if WIFI is already up
if [ -d /sys/class/net/wlan0 ]; then
	exit 0
fi

# Run initial setup sequence
wifi_setup

for i in $(seq 1 3); do

	# Up WIFI
	wifi_up

	# Check that WIFI interface is up
	if wifi_is_up; then
		echo "WIFI startup success"
		exit 0
	fi

	# Down WIFI
	wifi_down

	# Wait enough time for discharge
	sleep 5
done

echo "WIFI startup failed"

exit 1



