#!/bin/sh -e
#
# Variscite touch
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# This script disables ADS7846 Touchscreen if CTW6120 touch screen is available

# Check if CTW6120 touchscreen is available
if dmesg | grep -q " CTW6120: revid 0 touchscreen"; then
	echo "CTW6120 found disabling ADS784"
	export DISPLAY=:0.0
	xinput disable "ADS7846 Touchscreen"
fi

exit 0
