#!/bin/sh -e
#
# Activate Bluetooth for Variscite DART-6UL / VAR-SOM-MX7
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.

som=var-som-mx7
tuple_num=0x80

if [ "$som" = "dart-6ul" ]
then
	gpio_num=132
	tty_dev=ttymxc1
elif [ "$som" = "var-som-mx7" ]
then
	gpio_num=14
	tty_dev=ttymxc2
else
	exit 1
fi

(dmesg | grep -q "tuple $tuple_num") # Check if BT/WIFI is up
if [ $? -eq 0 ]
then
	echo "BT found"
else
	echo "No BT found"
	exit 0
fi

echo $gpio_num >/sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio${gpio_num}/direction
echo 0 > /sys/class/gpio/gpio${gpio_num}/value
sleep 0.1
echo 1 > /sys/class/gpio/gpio${gpio_num}/value

max() {
	printf "%s\n" "$@" | sort -g -r | head -n1
}

eth0_addr=$(cat /sys/class/net/eth0/address | sed 's/\://g')
eth1_addr=$(cat /sys/class/net/eth1/address | sed 's/\://g')
bd_addr_temp=$(max $eth0_addr $eth1_addr)
bd_addr_temp=$((0x$bd_addr_temp+1))
bd_addr_temp=$(printf '%012X' $bd_addr_temp)
bd_addr=$(echo $bd_addr_temp | sed 's/\(..\)/\1:/g;s/:$//')

brcm_patchram_plus --patchram /lib/firmware/bcm/bcm43430a1.hcd  --enable_hci --bd_addr ${bd_addr} --no2bytes --tosleep 1000 /dev/${tty_dev} &

sleep 2

/usr/libexec/bluetooth/bluetoothd &

hciconfig hci0 up

exit 0
